services:
  - type: web
    name: secondhand-marketplace-backend
    env: docker
    rootDir: backend
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "3306"
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false

  - type: web
    name: secondhand-marketplace-frontend
    env: static
    buildCommand: ""
    staticPublishPath: .
